### PR TITLE
Fix: Respect --no-frontend option (fixes #17)

### LINKED ISSUE #17: Conflicting `--no-frontend` and `--no-front-end` options
The [docs](http://sailsjs.org/documentation/reference/command-line-interface/sails-new) use `--no-frontend`, which prevents the .Gruntfile.js and `assets/` directories from being created.

However, the `package.json` and `.sailsrc` are only affected by `--no-front-end` (with the extra dash).  I think they should be combined under the `--no-frontend` as mentioned in the docs.

Edit: I think this might have been my fault (https://github.com/balderdashy/sails-generate-new/commit/f44bc75292df8590617c1641cf2d6da451813fbb#diff-2e48a6fbad35cab6228ee98ca3c6b038R60), I'll be happy to submit a fix...

### PR DESCRIPTION
**Pull request by IanVS**
I did this in a non-breaking way, in case anyone started to use the (incorrect) option `--no-front-end`.

### CODE REVIEW

**Comment by IanVS** [comment]
@particlebanana How's this look?

**Comment by sgress454** [comment]
@IanVS thanks for the PR.  Have you actually tested this?  It seems like checking `!scope.frontend` wouldn't work, because that check will evaluate to `true` in cases where `sails new` is called without any options at all.  That's why the existing check explicitly tests `scope['front-end']` against `false`.

Also, mind updating https://github.com/balderdashy/sails-generate-new/blob/master/lib/before.js#L35 to check `front-end` as well?

**Comment by IanVS** [comment]
Thanks for the review.  I can't say I checked generating without `--no-frontend`.  I only use sails as an API.  :)  I will update to explicitly check against false.  I was assuming `scope.frontend === true` by default without arguments, since by default all the frontend generators are applied.  I don't have a good understanding of `scope` and how it's set/used.

**Comment by IanVS** [comment]
@sgress454, I made the changes you asked for, and also am now excluding `views`, since those are also not needed without a front-end.

**Comment by konstantinzolotarev** [comment]
@IanVS @sgress454 Why not to do just like this:
```javascript
if (scope['font-end'] === false) {
  scope.frontend = false;
} 
```

Is it really require to check both arguments everywhere ?

**Comment by IanVS** [comment]
Technically, the only one needed is `scope.frontend === false`. I was concerned about breaking functionally if anyone started using `--no-front-end`.  My preference would be to only support the official version `--no-frontend`, but I was concerned about making a "breaking"  change.

**Comment by sgress454** [comment]
@konstantinzolotarev good call, we can just default the one setting to the other in `before.js` and then just check for `scope.frontend===false` everywhere else instead of having to always check both.

**Comment by IanVS** [comment]
Got it, will do.

**Comment by IanVS** [comment]
OK, anything else I should change?

**Comment by konstantinzolotarev** [comment]
Ok for me.
@IanVS Thank you !

**Comment by IanVS** [comment]
Thanks for merging.  Will you be creating a new release?

**Comment by konstantinzolotarev** [comment]
Sure.

**Pull request merged**
