### PR TITLE
[Feature] Ability to configure package.json file for other generators. 

### PR DESCRIPTION
**Pull request by konstantinzolotarev**
Using `packagejson` scope option.

For example new dependencies could be added to newly created package.json file if some generator will add such options to scope: 

```
packagejson: {
    dependencies: {
        jade: '*'
    }
}
```

Feature will be very useful for new views generators.

### CODE REVIEW

**Comment by CWyrtzen** [comment]
Scheduled for bump~

**Comment by konstantinzolotarev** [comment]
@CWyrtzen @rachaelshaw Any news on this ?

**Comment by tjwebb** [comment]
@mikermcneil would you mind taking a quick look at this?

**Comment by konstantinzolotarev** [comment]
@mikermcneil @rachaelshaw @CWyrtzen Please somebody take a look.

**Comment by mikermcneil** [comment]
@konstantinzolotarev looks good- only things I'd ask are:

1. please format the code using the .editorconfig file so the spacing is normalized (i.e. two spaces for indentation).
2. Just for consistency, can we call it `packageJson` instead of `packagejson`? 

Thanks!

**Comment by konstantinzolotarev** [comment]
Updated

**Pull request merged**
